---
- name: List Webex Workspaces
  hosts: local
  gather_facts: false
  vars:
    webex_token: "{{ lookup('env', 'WEBEX_TOKEN') }}"
  tasks:
    - name: Call Webex API
      uri:
        url: "https://webexapis.com/v1/workspaces"
        method: GET
        headers:
          Authorization: "Bearer {{ webex_token }}"
        ca_path: "/Users/ramvelez/collab-as-code/.venv/lib/python3.13/site-packages/certifi/cacert.pem"
        return_content: true
      register: result

    - name: Print only Room workspaces
      debug:
        msg: "{{ item.displayName }}"
      loop: "{{ result.json['items'] }}"
      when: "'Unit' in item.displayName"
